server:
  port: 8080

spring:
  application:
    name: exchange-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/bank/protocol/openid-connect/certs

management.endpoints.web.exposure.include: health,info

logging.level.org.springframework.security: INFO
