server:
  port: 8080

spring:
  application:
    name: accounts-service

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC

  liquibase:
    enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/bank/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: health,info,env

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.consul.config: DEBUG
    org.springframework.cloud.consul: DEBUG
