server:
  port: 8080

spring:
  application:
    name: blocker-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/bank/protocol/openid-connect/certs

blocker:
  random-block-percent: 3        # вероятность блокировки, %
  night-start-hour: 0            # 0..23 (UTC)
  night-end-hour: 6
  night-amount-threshold: 50000  # всё что >= — подозрительно ночью
  max-amount: 1_000_000          # защитный порог, слишком большие суммы рубим

management.endpoints.web.exposure.include: health,info
logging.level.org.springframework.security: INFO
